---
- hosts: localhost
  connection: local
  
  vars_prompt:
  - name: sudo_password
    prompt: "Enter sudo password"
    private: yes

  vars:
    php_extensions:
    - php7.4-bcmath
    - php7.4-curl
    - php7.4-gettext
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-pdo
    - php7.4-sqlite3
    - php7.4-xml
    - php7.4-zip
    created_domains:
    - { name: 'phpmyadmin', domain: 'pma.local', path: "{{ '/usr/local/var/www/phpmyadmin' if ansible_facts['os_family'] == 'Darwin' else '/var/www/html/phpmyadmin' }}" }
    - { name: 'mailhog', domain: 'mailhog.local', proxy: "http://localhost:8025/" }
    enabled_sites:
    - { name: 'phpmyadmin' }
    - { name: 'mailhog' }

  tasks:
  - name: Check current user
    fail: msg="Do not run ansible-playbook as root"
    when: ansible_env.USER == 'root'
  - import_role:
      name: "system"
  - import_role:
      name: "apache2"
      tasks_from: install
  - import_role:
      name: "php7"
  - import_role:
      name: "mysql"
  - import_role:
      name: "phpmyadmin"
  - import_role:
      name: "apache2"
      tasks_from: setup-hosts
  - import_role:
      name: "mailhog"