- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: "{{ sudo_password }}"

- name: Update homebrew cache
  homebrew:
    update_homebrew: yes
  when: ansible_facts['os_family'] == 'Darwin'

- block:

  - name: Install apache2 server
    package:
      name:
      - apache2
      state: latest

  become: "{{ 'no' if ansible_facts['os_family'] == 'Darwin' else 'yes' }}"
  become_method: sudo
  vars:
    ansible_become_password: "{{ sudo_password }}"

- block:

  - name: Ensure AcceptFilter http none is present in apache config
    lineinfile:
      path: "/etc/apache2/{{ 'httpd' if ansible_facts['os_family'] == 'Darwin' else 'apache2' }}.conf"
      line: AcceptFilter http none
      state: present
    tags: [ apache ]
    notify:
    - restart apache2

  - name: Ensure AcceptFilter https none is present in apache config
    lineinfile:
      path: "/etc/apache2/{{ 'httpd' if ansible_facts['os_family'] == 'Darwin' else 'apache2' }}.conf"
      line: AcceptFilter https none
      state: present
    tags: [ apache ]
    notify:
    - restart apache2

  - name: Ensure Mac Os X include vhosts
    lineinfile:
      path: "/etc/apache2/{{ 'httpd' if ansible_facts['os_family'] == 'Darwin' else 'apache2' }}.conf"
      line: Include /private/etc/apache2/vhosts/*.conf
      state: present
    tags: [ apache ]
    when: ansible_facts['os_family'] == 'Darwin'
    notify:
    - restart apache2

  - name: Start service apache2, if not started
    service:
      name: apache2
      state: started
    tags: [ apache ]
  
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: "{{ sudo_password }}"