- name: Ensure websites are enabled (or disabled)
  file:
    src: "/etc/apache2/sites-available/{{ item }}"
    dest: "/etc/apache2/sites-enabled/{{ item }}"
    state: link
  with_items:
    - "000-default.conf"
  tags: [ apache ]
  when: ansible_facts['os_family'] == 'Debian'
  notify:
    - restart apache2
