- name: restart php7
  service:
    name: php7.4-fpm
    state: restarted
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: "{{ sudo_password }}"
  when: ansible_facts['os_family'] == 'Debian'

- name: restart php7
  command: "brew services restart php@7.4"
  when: ansible_facts['os_family'] == 'Darwin'