- name: Install homebrew (it takes a while)
  shell: >
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: "{{ sudo_password }}"

- name: Update homebrew cache
  homebrew:
    update_homebrew: yes
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install software with raised privileges
  block:
  
  - name: Install system software
    package:
      name:
      - python-apt
      - git
      - curl
      state: latest
  
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: "{{ sudo_password }}"

- name: Install software with standard privileges
  block:

  - name: Install python modules with pip
    pip:
      name:
        - pymysql
        - docker
      extra_args: --user
    
  - name: Install nvm
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  
- name: Debian / Ubuntu only
  block:
  - name: Reload bashrc
    shell: >
      . "{{ ansible_env.HOME }}/.bashrc"

  - name: Add homebrew to .profile
    shell: >
      echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> {{ ansible_env.HOME }}/.profile

  - name: Reload profile
    shell: >
      . "{{ ansible_env.HOME }}/.profile"
  when: ansible_facts['os_family'] == 'Debian'